FROM php:8.3.13-fpm-alpine3.20

COPY conf.d/*.ini $PHP_INI_DIR/conf.d/

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apk update \
  && apk add --no-cache \
    icu-dev zlib-dev libpng-dev bzip2-dev libzip-dev openldap-dev \
  && docker-php-ext-install \
    intl mysqli gd exif bz2 zip ldap opcache \ 
  && apk add --no-cache pcre-dev ${PHPIZE_DEPS} \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && apk del pcre-dev ${PHPIZE_DEPS}

RUN docker-php-source delete

EXPOSE 9000/tcp 

CMD ["php-fpm"]

