FROM php:8.4.13-fpm-alpine3.22

COPY conf.d/*.ini $PHP_INI_DIR/conf.d/

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apk update \
  && apk add --no-cache \
    icu-dev \
    zlib-dev \
    libpng-dev \
    bzip2-dev \
    libzip-dev \
    openldap-dev \
  && docker-php-ext-install \
    intl mysqli gd exif bz2 zip ldap opcache bcmath \
  && apk add --no-cache --virtual .build-deps \
    autoconf \
    dpkg-dev \
    dpkg \
    file \
    g++ \
    gcc \
    musl-dev \
    make \
    pkgconf \
    re2c \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && apk del .build-deps

RUN docker-php-source delete

EXPOSE 9000/tcp 

CMD ["php-fpm"]

