FROM php:8.5.11-fpm-alpine3.24

COPY conf.d/*.ini $PHP_INI_DIR/conf.d/

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apk update \
  && apk add --no-cache \
    icu-dev=78.1-r0 \
    zlib-dev=1.3.2-r0 \
    libpng-dev=1.6.59-r0 \
    bzip2-dev=1.0.8-r6 \
    libzip-dev=1.11.4-r2 \
    openldap-dev=2.6.15-r0 \
  && docker-php-ext-install \
    intl mysqli gd exif bz2 zip ldap bcmath \
  && apk add --no-cache --virtual .build-deps \
    autoconf=2.73-r0 \
    dpkg-dev=1.23.7-r0 \
    dpkg=1.23.7-r0 \
    file=5.47-r2 \
    g++=15.2.0-r5 \
    gcc=15.2.0-r5 \
    musl-dev=1.2.6-r2 \
    make=4.4.1-r4 \
    pkgconf=2.5.1-r0 \
    re2c=4.5.1-r0 \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && apk del .build-deps

RUN docker-php-source delete

EXPOSE 9000/tcp 

CMD ["php-fpm"]

