{{- if and (include "glpi.backup.enabled" .) (not .Values.glpi.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glpi.backup.secretName" . }}
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.glpi.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.glpi.backup.s3.accessKey | quote }}
  {{ .Values.glpi.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.glpi.backup.s3.secretKey | quote }}
{{- end }}
