{{- if .Values.mariadb.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  name: mariadb
  namespace: {{ include "glpi.namespace" . }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.mariadb.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "glpi.selectorLabels" . | nindent 6 }}
      role: primary
  serviceName: mariadb-headless
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: primary
        role: primary
      name: mariadb
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
        {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "glpi.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: primary
              namespaces:
                - {{ include "glpi.namespace" . }}
              topologyKey: kubernetes.io/hostname
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 120
      containers:
        - image: {{ include "glpi.mariadb.image" . }}
          name: mariadb
          {{- with .Values.mariadb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: mariadb-glpi-secret
          ports:
            - containerPort: 3306
              name: mariadb
              protocol: TCP
          resources:
            {{- toYaml .Values.mariadb.primary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/var/lib/mysql"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "glpi.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.mariadb.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.mariadb.persistence.size }}
        {{- if .Values.mariadb.persistence.storageClass }}
        storageClassName: {{ .Values.mariadb.persistence.storageClass }}
        {{- end }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
  name: mariadb-headless
  namespace: {{ include "glpi.namespace" . }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mariadb
      port: {{ .Values.mariadb.service.port }}
      protocol: TCP
      targetPort: {{ .Values.mariadb.service.port }}
  publishNotReadyAddresses: true
  selector:
    {{- include "glpi.selectorLabels" . | nindent 4 }}
    role: primary
  sessionAffinity: None
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
  name: mariadb
  namespace: {{ include "glpi.namespace" . }}
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mariadb
      port: {{ .Values.mariadb.service.port }}
      protocol: TCP
      targetPort: {{ .Values.mariadb.service.port }}
  selector:
    {{- include "glpi.selectorLabels" . | nindent 4 }}
    role: primary
  sessionAffinity: None
  type: {{ .Values.mariadb.service.type }}
{{- end }}
