{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mariadb-glpi-secret
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.username | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
{{- end }}
