version: "3.5"
services:
  mariadb: 
    image: mariadb:10.6
    restart: unless-stopped
    volumes: 
      - mariadb-glpi-volume:/var/lib/mysql:rw
    environment: 
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi 
      MYSQL_PASSWORD: glpi 
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
    ports: 
      - 3306:3306
  glpi-db-install:
    image: eftechcombr/glpi:php-fpm-10.0.7
    restart: on-failure 
    env_file: ./.env
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw    
    depends_on: 
      - mariadb
    command: 
      - /usr/local/bin/glpi-db-install.sh
  glpi-verify-dir: 
    image: eftechcombr/glpi:php-fpm-10.0.7
    restart: on-failure
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    command: 
      - /usr/local/bin/glpi-verify-dir.sh
  glpi-db-configure: 
    image: eftechcombr/glpi:php-fpm-10.0.7
    restart: on-failure
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    command: 
      - /usr/local/bin/glpi-db-configure.sh
  php: 
    build: php/
    image: eftechcombr/glpi:php-fpm-10.0.7
    restart: unless-stopped
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - mariadb
      - glpi-db-install
      - glpi-db-configure
      - glpi-verify-dir
    ports: 
      - "9000:9000"
  nginx: 
    build: nginx/
    image: eftechcombr/glpi:nginx-10.0.7
    restart: unless-stopped
    ports: 
      - "8080:80"
    depends_on: 
      - php
volumes: 
  glpi-marketplace:
  glpi-files:
  glpi-etc:
  glpi-install:
  mariadb-glpi-volume: 
#networks: 
#  glpi-frontend: 
#  glpi-backend:
