apiVersion: v1
kind: ConfigMap
metadata:
  name: glpi-config
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
data:
  GLPI_LANG: {{ .Values.glpi.language | quote }}
  VERSION: {{ .Values.glpi.version | quote }}
  GLPI_MARKETPLACE_DIR: {{ .Values.glpi.paths.marketplace }}
  GLPI_VAR_DIR: {{ .Values.glpi.paths.var }}
  GLPI_DOC_DIR: /var/www/html
  GLPI_CRON_DIR: {{ .Values.glpi.paths.var }}/_cron
  GLPI_DUMP_DIR: {{ .Values.glpi.paths.var }}/_dumps
  GLPI_GRAPH_DIR: {{ .Values.glpi.paths.var }}/_graphs
  GLPI_LOCK_DIR: {{ .Values.glpi.paths.var }}/_lock
  GLPI_LOG_DIR: {{ .Values.glpi.paths.var }}/_log
  GLPI_PICTURE_DIR: {{ .Values.glpi.paths.var }}/_pictures
  GLPI_PLUGIN_DOC_DIR: {{ .Values.glpi.paths.var }}/_plugins
  GLPI_RSS_DIR: {{ .Values.glpi.paths.var }}/_rss
  GLPI_SESSION_DIR: {{ .Values.glpi.paths.var }}/_sessions
  GLPI_TMP_DIR: {{ .Values.glpi.paths.var }}/_tmp
  GLPI_UPLOAD_DIR: {{ .Values.glpi.paths.var }}/_uploads
  GLPI_CACHE_DIR: {{ .Values.glpi.paths.var }}/_cache
  GLPI_CONFIG_DIR: {{ .Values.glpi.paths.config }}

  {{- if .Values.mariadb.enabled }}
  MARIADB_HOST: "mariadb-headless.{{ include "glpi.namespace" . }}.svc.cluster.local"
  MARIADB_PORT: {{ .Values.mariadb.service.port | quote }}
  {{- else }}
  MARIADB_HOST: {{ .Values.externalDatabase.host | quote }}
  MARIADB_PORT: {{ .Values.externalDatabase.port | quote }}
  {{- end }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    name: nginx-conf
data:
  default.conf: |-
    server {
        listen 8080;
        listen [::]:8080;

        server_name glpi.localhost;

        root /var/www/html/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php$ {
            fastcgi_pass php-fpm.{{ include "glpi.namespace" . }}.svc.cluster.local:9000;

            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
