{{- if not .Values.glpi.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: glpi-secret
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.username | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- else if .Values.externalDatabase }}
  MARIADB_DATABASE: {{ .Values.externalDatabase.database | b64enc | quote }}
  MARIADB_USER: {{ .Values.externalDatabase.username | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
