apiVersion: v1
kind: Secret
metadata:
  name: glpi-secret
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.username | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
  
