{{- if .Values.glpi.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: glpi-cronjob
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.glpi.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1 
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.glpi.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - image: {{ include "glpi.phpfpm.image" . }}
              imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
              name: base
              {{- with .Values.glpi.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              envFrom: 
                - configMapRef: 
                    name: glpi-config
                - secretRef: 
                    name: glpi-secret
              command: 
                - php
                - front/cron.php
              volumeMounts:
                - name: files 
                  mountPath: /var/lib/glpi
                - name: marketplace
                  mountPath: /var/www/html/marketplace
                - name: etc 
                  mountPath: /etc/glpi
                - name: php-config
                  mountPath: /usr/local/etc/php/conf.d/zz-helm-custom.ini
                  subPath: zz-helm-custom.ini
              resources:
                {{- toYaml .Values.glpi.phpfpm.resources | nindent 16 }}
          volumes: 
            - name: etc
              persistentVolumeClaim:
                claimName: glpi-etc
            - name: files
              persistentVolumeClaim:
                claimName: glpi-files
            - name: marketplace
              persistentVolumeClaim:
                claimName: glpi-marketplace
            - name: php-config
              configMap:
                name: glpi-php-config
          restartPolicy: OnFailure
{{- end }}
