{{- if .Values.glpi.jobs.verifyDir.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glpi-verify-dir
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.glpi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ include "glpi.phpfpm.image" . }}
          imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
          name: base
          {{- with .Values.glpi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: glpi-config
            - secretRef:
                name: glpi-secret
          command:
            - sh
            - -c
            - "/usr/local/bin/glpi-verify-dir.sh"
          volumeMounts:
            - name: files
              mountPath: /var/lib/glpi
            - name: marketplace
              mountPath: /var/www/html/marketplace
            - name: etc
              mountPath: /etc/glpi
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: glpi-etc
        - name: files
          persistentVolumeClaim:
            claimName: glpi-files
        - name: marketplace
          persistentVolumeClaim:
            claimName: glpi-marketplace
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}


{{- if .Values.glpi.jobs.dbInstall.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glpi-db-install
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.glpi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mariadb
          image: busybox:1.36.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          command:
            - sh
            - -c
            - until nc -z $MARIADB_HOST $MARIADB_PORT; do sleep 2; done
          envFrom:
            - configMapRef:
                name: glpi-config
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      containers:
        - image: {{ include "glpi.phpfpm.image" . }}
          imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
          name: base
          {{- with .Values.glpi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - "/usr/local/bin/glpi-db-install.sh"
          envFrom:
            - configMapRef:
                name: glpi-config
            - secretRef:
                name: glpi-secret
          volumeMounts:
            - name: files
              mountPath: /var/lib/glpi
            - name: marketplace
              mountPath: /var/www/html/marketplace
            - name: etc
              mountPath: /etc/glpi
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: glpi-etc
        - name: files
          persistentVolumeClaim:
            claimName: glpi-files
        - name: marketplace
          persistentVolumeClaim:
            claimName: glpi-marketplace
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}


{{- if .Values.glpi.jobs.dbUpgrade.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glpi-db-upgrade
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.glpi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mariadb
          image: busybox:1.36.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          command:
            - sh
            - -c
            - until nc -z $MARIADB_HOST $MARIADB_PORT; do sleep 2; done
          envFrom:
            - configMapRef:
                name: glpi-config
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      containers:
        - image: {{ include "glpi.phpfpm.image" . }}
          imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
          name: base
          {{- with .Values.glpi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - "/usr/local/bin/glpi-db-upgrade.sh"
          envFrom:
            - configMapRef:
                name: glpi-config
            - secretRef:
                name: glpi-secret
          volumeMounts:
            - name: files
              mountPath: /var/lib/glpi
            - name: marketplace
              mountPath: /var/www/html/marketplace
            - name: etc
              mountPath: /etc/glpi
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: glpi-etc
        - name: files
          persistentVolumeClaim:
            claimName: glpi-files
        - name: marketplace
          persistentVolumeClaim:
            claimName: glpi-marketplace
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}


{{- if .Values.glpi.jobs.dbConfigure.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glpi-db-configure
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.glpi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mariadb
          image: busybox:1.36.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          command:
            - sh
            - -c
            - until nc -z $MARIADB_HOST $MARIADB_PORT; do sleep 2; done
          envFrom:
            - configMapRef:
                name: glpi-config
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      containers:
        - image: {{ include "glpi.phpfpm.image" . }}
          imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
          name: base
          {{- with .Values.glpi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - "/usr/local/bin/glpi-db-configure.sh"
          envFrom:
            - configMapRef:
                name: glpi-config
            - secretRef:
                name: glpi-secret
          volumeMounts:
            - name: etc
              mountPath: /etc/glpi
            - name: files
              mountPath: /var/lib/glpi
            - name: marketplace
              mountPath: /var/www/html/marketplace
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: glpi-etc
        - name: files
          persistentVolumeClaim:
            claimName: glpi-files
        - name: marketplace
          persistentVolumeClaim:
            claimName: glpi-marketplace
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}


{{- if .Values.glpi.jobs.cacheConfigure.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glpi-cache-configure
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.glpi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ include "glpi.phpfpm.image" . }}
          imagePullPolicy: {{ .Values.glpi.phpfpm.image.pullPolicy }}
          name: base
          {{- with .Values.glpi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - "/usr/local/bin/glpi-cache-configure.sh"
          envFrom:
            - configMapRef:
                name: glpi-config
            - secretRef:
                name: glpi-secret
          volumeMounts:
            - name: etc
              mountPath: /etc/glpi
            - name: files
              mountPath: /var/lib/glpi
            - name: marketplace
              mountPath: /var/www/html/marketplace
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: glpi-etc
        - name: files
          persistentVolumeClaim:
            claimName: glpi-files
        - name: marketplace
          persistentVolumeClaim:
            claimName: glpi-marketplace
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}
