{{- if .Values.mariadb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-timezone
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      {{- with .Values.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mariadb
          image: busybox:1.36.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          command:
            - sh
            - -c
            - until nc -z $MARIADB_HOST $MARIADB_PORT; do sleep 2; done
          envFrom:
            - configMapRef:
                name: mariadb-glpi-config
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      containers:
        - image: {{ include "glpi.mariadb.image" . }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          name: base
          {{- with .Values.mariadb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              mariadb --host=${MARIADB_HOST} -u root -p${MARIADB_ROOT_PASSWORD} \
                -e "GRANT SELECT ON mysql.time_zone_name TO '{{ .Values.mariadb.auth.username }}'@'%'; FLUSH PRIVILEGES;"
          envFrom:
            - secretRef:
                name: mariadb-glpi-secret
            - configMapRef:
                name: mariadb-glpi-config
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
{{- end }}
