{{- if .Values.mariadb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-timezone
  namespace: {{ include "glpi.namespace" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ include "glpi.mariadb.image" . }}
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        name: base
        {{- with .Values.mariadb.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - sh
        - -c 
        - "mariadb --host=${MARIADB_HOST} -u root -p${MARIADB_ROOT_PASSWORD} -e \"GRANT SELECT ON mysql.time_zone_name TO 'glpi'@'%'; FLUSH PRIVILEGES;\""
        envFrom: 
        - secretRef: 
            name: mariadb-glpi-secret
        - configMapRef: 
            name: mariadb-glpi-config
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
status: {}
{{- end }}

