{{- if .Values.mariadb.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
{{ include "glpi.labels" . | indent 4 }}
    app.kubernetes.io/component: primary
  name: mariadb
  namespace: {{ include "glpi.namespace" . }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.mariadb.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
{{ include "glpi.selectorLabels" . | indent 6 }}
      role: primary
  serviceName: mariadb-headless
  template:
    metadata:
      labels:
{{ include "glpi.labels" . | indent 8 }}
        app.kubernetes.io/component: primary
        role: primary
      name: mariadb
    spec:
      {{- with .Values.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
{{ include "glpi.selectorLabels" . | indent 18 }}
                  app.kubernetes.io/component: primary
              namespaces:
              - {{ include "glpi.namespace" . }}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: {{ include "glpi.mariadb.image" . }}
        name: mariadb
        {{- with .Values.mariadb.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        envFrom: 
        - secretRef: 
            name: mariadb-glpi-secret
        ports:
        - containerPort: 3306
          name: mariadb
          protocol: TCP
        resources:
{{ toYaml .Values.mariadb.primary.resources | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: "/var/lib/mysql"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes: 
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-data
  updateStrategy:
    type: OnDelete
status: 
  replicas: {{ .Values.mariadb.replicaCount }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "glpi.labels" . | indent 4 }}
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mariadb-headless
  namespace: {{ include "glpi.namespace" . }}
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mariadb 
    port: {{ .Values.mariadb.service.port }}
    protocol: TCP
    targetPort: {{ .Values.mariadb.service.port }}
  publishNotReadyAddresses: true
  selector:
{{ include "glpi.selectorLabels" . | indent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "glpi.labels" . | indent 4 }}
  name: mariadb
  namespace: {{ include "glpi.namespace" . }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mariadb
    port: {{ .Values.mariadb.service.port }}
    protocol: TCP
    targetPort: {{ .Values.mariadb.service.port }}
  selector:
{{ include "glpi.selectorLabels" . | indent 4 }}
    role: primary
  sessionAffinity: None
  type: {{ .Values.mariadb.service.type }}
status:
  loadBalancer: {}
{{- end }}




